/**
 * Inventory Router - الأصول والعهد
 */
import { z } from "zod";
import { eq, like, and, or, sql, desc } from "drizzle-orm";
import { protectedProcedure, router } from "../_core/trpc";
import { getDb } from "../db";
import {
  assets,
  custodyItems,
  employees,
  departments,
  locations,
  archiveDocuments,
} from "../../drizzle/schema";
import { logAuditAction } from "../security";
import { TRPCError } from "@trpc/server";

// =============================================
// دالة مساعدة: توليد وثيقة أرشيف تلقائية
// =============================================
async function upsertArchiveDocument(params: {
  db: any;
  entityType: "asset" | "custody";
  entityId: number;
  entityName: string;
  entityCode: string | null;
  employeeName: string | null;
  departmentName: string | null;
  locationName: string | null;
  quantity: number;
  assetValue: string | null;
  condition: string | null;
  status: string;
  notes: string | null;
  assetImagePath: string | null;
  createdBy: number;
  isUpdate: boolean;
}) {
  const {
    db, entityType, entityId, entityName, entityCode, employeeName,
    departmentName, locationName, quantity, assetValue, condition,
    status, notes, assetImagePath, createdBy, isUpdate,
  } = params;

  const label = entityType === "asset" ? "أصل" : "عهدة";
  const operationType = isUpdate ? "تحديث" : "إضافة";
  const documentTitle = `${label}: ${entityName}${entityCode ? ` (${entityCode})` : ""}`;
  const fileName = `${entityType}_${entityId}_${Date.now()}.html`;

  // إذا كان تحديثاً، نحدّث السجل الموجود إن وُجد
  if (isUpdate) {
    const existing = await db
      .select({ id: archiveDocuments.id })
      .from(archiveDocuments)
      .where(
        entityType === "asset"
          ? eq(archiveDocuments.assetId, entityId)
          : eq(archiveDocuments.custodyId, entityId)
      )
      .orderBy(desc(archiveDocuments.createdAt))
      .limit(1);

    if (existing.length > 0) {
      await db.update(archiveDocuments).set({
        documentTitle,
        fileName,
        operationType,
        notes: notes || null,
        isAutoGenerated: true,
      }).where(eq(archiveDocuments.id, existing[0].id));
      return { id: existing[0].id, updated: true };
    }
  }

  // إنشاء سجل جديد
  const result = await db.insert(archiveDocuments).values({
    entityType,
    operationType,
    assetId: entityType === "asset" ? entityId : null,
    custodyId: entityType === "custody" ? entityId : null,
    documentTitle,
    fileName,
    filePath: null,
    notes: notes || null,
    isAutoGenerated: true,
    createdBy,
  });
  return { id: Number(result[0].insertId), updated: false };
}

// =============================================
// الأصول
// =============================================
const assetsRouter = router({
  list: protectedProcedure
    .input(z.object({
      search: z.string().optional(),
      departmentId: z.number().optional(),
      locationId: z.number().optional(),
      status: z.string().optional(),
    }).optional())
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const conditions: any[] = [];
      if (input?.search) {
        conditions.push(
          or(
            like(assets.assetName, `%${input.search}%`),
            like(assets.assetCode, `%${input.search}%`)
          )
        );
      }
      if (input?.departmentId) conditions.push(eq(assets.departmentId, input.departmentId));
      if (input?.locationId) conditions.push(eq(assets.locationId, input.locationId));
      if (input?.status) conditions.push(eq(assets.status, input.status));

      const where = conditions.length > 0 ? and(...conditions) : undefined;

      const rows = await db
        .select({
          id: assets.id,
          assetName: assets.assetName,
          assetCode: assets.assetCode,
          quantity: assets.quantity,
          assetValue: assets.assetValue,
          condition: assets.condition,
          assignedTo: assets.assignedTo,
          employeeName: employees.fullName,
          departmentId: assets.departmentId,
          departmentName: departments.name,
          locationId: assets.locationId,
          locationName: locations.name,
          status: assets.status,
          notes: assets.notes,
          assetImagePath: assets.assetImagePath,
          invoiceImagePath: assets.invoiceImagePath,
          excludedQuantity: assets.excludedQuantity,
          createdAt: assets.createdAt,
          updatedAt: assets.updatedAt,
        })
        .from(assets)
        .leftJoin(employees, eq(assets.assignedTo, employees.id))
        .leftJoin(departments, eq(assets.departmentId, departments.id))
        .leftJoin(locations, eq(assets.locationId, locations.id))
        .where(where)
        .orderBy(desc(assets.createdAt));

      return rows;
    }),

  getById: protectedProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const [row] = await db
        .select({
          id: assets.id,
          assetName: assets.assetName,
          assetCode: assets.assetCode,
          quantity: assets.quantity,
          assetValue: assets.assetValue,
          condition: assets.condition,
          assignedTo: assets.assignedTo,
          employeeName: employees.fullName,
          departmentId: assets.departmentId,
          departmentName: departments.name,
          locationId: assets.locationId,
          locationName: locations.name,
          status: assets.status,
          notes: assets.notes,
          assetImagePath: assets.assetImagePath,
          invoiceImagePath: assets.invoiceImagePath,
          excludedQuantity: assets.excludedQuantity,
          createdAt: assets.createdAt,
        })
        .from(assets)
        .leftJoin(employees, eq(assets.assignedTo, employees.id))
        .leftJoin(departments, eq(assets.departmentId, departments.id))
        .leftJoin(locations, eq(assets.locationId, locations.id))
        .where(eq(assets.id, input.id))
        .limit(1);
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "الأصل غير موجود" });
      return row;
    }),

  create: protectedProcedure
    .input(z.object({
      assetName: z.string().min(1).max(500),
      assetCode: z.string().max(100).optional().nullable(),
      quantity: z.number().min(1).default(1),
      assetValue: z.string().optional().nullable(),
      condition: z.string().max(50).optional().nullable(),
      assignedTo: z.number().optional().nullable(),
      departmentId: z.number().optional().nullable(),
      locationId: z.number().optional().nullable(),
      notes: z.string().optional().nullable(),
      assetImagePath: z.string().optional().nullable(),
      invoiceImagePath: z.string().optional().nullable(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const result = await db.insert(assets).values({
        assetName: input.assetName,
        assetCode: input.assetCode || null,
        quantity: input.quantity,
        assetValue: input.assetValue || "0",
        condition: input.condition || "جيد جدًا",
        assignedTo: input.assignedTo || null,
        departmentId: input.departmentId || null,
        locationId: input.locationId || null,
        notes: input.notes || null,
        assetImagePath: input.assetImagePath || null,
        invoiceImagePath: input.invoiceImagePath || null,
        status: "ACTIVE",
      });
      const insertId = Number(result[0].insertId);
      // أرشفة تلقائية عند إضافة أصل جديد
      try {
        await upsertArchiveDocument({
          db,
          entityType: "asset",
          entityId: insertId,
          entityName: input.assetName,
          entityCode: input.assetCode || null,
          employeeName: null,
          departmentName: null,
          locationName: null,
          quantity: input.quantity,
          assetValue: input.assetValue || null,
          condition: input.condition || null,
          status: "ACTIVE",
          notes: input.notes || null,
          assetImagePath: input.assetImagePath || null,
          createdBy: ctx.user.id,
          isUpdate: false,
        });
      } catch (archiveErr) {
        console.error("[Archive] فشل إنشاء سجل الأرشيف:", archiveErr);
      }
      await logAuditAction({
        tableName: "assets",
        recordId: insertId,
        actionType: "CREATE",
        actionDescription: `إضافة أصل: ${input.assetName}`,
        newData: input,
        performedBy: ctx.user.id,
        performedByName: ctx.user.name || undefined,
        ipAddress: ctx.req.ip || undefined,
        userAgent: ctx.req.headers["user-agent"] || undefined,
      });
      return { id: insertId };
    }),

  update: protectedProcedure
    .input(z.object({
      id: z.number(),
      assetName: z.string().min(1).max(500),
      assetCode: z.string().max(100).optional().nullable(),
      quantity: z.number().min(1).default(1),
      assetValue: z.string().optional().nullable(),
      condition: z.string().max(50).optional().nullable(),
      assignedTo: z.number().optional().nullable(),
      departmentId: z.number().optional().nullable(),
      locationId: z.number().optional().nullable(),
      status: z.string().max(30).optional(),
      notes: z.string().optional().nullable(),
      assetImagePath: z.string().optional().nullable(),
      invoiceImagePath: z.string().optional().nullable(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const [old] = await db.select().from(assets).where(eq(assets.id, input.id)).limit(1);
      if (!old) throw new TRPCError({ code: "NOT_FOUND" });
      const { id, ...updateData } = input;
      await db.update(assets).set({
        assetName: updateData.assetName,
        assetCode: updateData.assetCode || null,
        quantity: updateData.quantity,
        assetValue: updateData.assetValue || "0",
        condition: updateData.condition || null,
        assignedTo: updateData.assignedTo || null,
        departmentId: updateData.departmentId || null,
        locationId: updateData.locationId || null,
        status: updateData.status || old.status,
        notes: updateData.notes || null,
        assetImagePath: updateData.assetImagePath || null,
        invoiceImagePath: updateData.invoiceImagePath || null,
      }).where(eq(assets.id, id));
      // تحديد الحقول المتغيرة
      const changedFields: string[] = [];
      if (old.assetName !== updateData.assetName) changedFields.push('assetName');
      if (old.assetCode !== (updateData.assetCode || null)) changedFields.push('assetCode');
      if (old.quantity !== updateData.quantity) changedFields.push('quantity');
      if (old.assetValue !== (updateData.assetValue || '0')) changedFields.push('assetValue');
      if (old.condition !== (updateData.condition || null)) changedFields.push('condition');
      if (old.assignedTo !== (updateData.assignedTo || null)) changedFields.push('assignedTo');
      if (old.departmentId !== (updateData.departmentId || null)) changedFields.push('departmentId');
      if (old.locationId !== (updateData.locationId || null)) changedFields.push('locationId');
      if (old.status !== (updateData.status || old.status)) changedFields.push('status');
      if (old.notes !== (updateData.notes || null)) changedFields.push('notes');

      // أرشفة تلقائية عند تعديل أصل
      try {
        await upsertArchiveDocument({
          db,
          entityType: "asset",
          entityId: id,
          entityName: updateData.assetName,
          entityCode: updateData.assetCode || null,
          employeeName: null,
          departmentName: null,
          locationName: null,
          quantity: updateData.quantity,
          assetValue: updateData.assetValue || null,
          condition: updateData.condition || null,
          status: updateData.status || old.status,
          notes: updateData.notes || null,
          assetImagePath: updateData.assetImagePath || null,
          createdBy: ctx.user.id,
          isUpdate: true,
        });
      } catch (archiveErr) {
        console.error("[Archive] فشل تحديث سجل الأرشيف:", archiveErr);
      }
      await logAuditAction({
        tableName: "assets",
        recordId: id,
        actionType: "UPDATE",
        actionDescription: `تعديل أصل: ${input.assetName} - تغيير ${changedFields.length} حقل`,
        oldData: old,
        newData: updateData,
        changedFields,
        performedBy: ctx.user.id,
        performedByName: ctx.user.name || undefined,
        ipAddress: ctx.req.ip || undefined,
        userAgent: ctx.req.headers["user-agent"] || undefined,
      });
      return { success: true };
    }),

  delete: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const [old] = await db.select().from(assets).where(eq(assets.id, input.id)).limit(1);
      if (!old) throw new TRPCError({ code: "NOT_FOUND" });
      await db.delete(assets).where(eq(assets.id, input.id));
      await logAuditAction({
        tableName: "assets",
        recordId: input.id,
        actionType: "DELETE",
        actionDescription: `حذف أصل: ${old.assetName}`,
        oldData: old,
        performedBy: ctx.user.id,
        performedByName: ctx.user.name || undefined,
        ipAddress: ctx.req.ip || undefined,
        userAgent: ctx.req.headers["user-agent"] || undefined,
      });
      return { success: true };
    }),

  stats: protectedProcedure.query(async () => {
    const db = await getDb();
    if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
    const [result] = await db
      .select({
        total: sql<number>`COUNT(*)`,
        totalValue: sql<string>`COALESCE(SUM(CAST(${assets.assetValue} AS DECIMAL(12,2)) * ${assets.quantity}), 0)`,
        activeCount: sql<number>`SUM(CASE WHEN ${assets.status} = 'ACTIVE' THEN 1 ELSE 0 END)`,
      })
      .from(assets);
    return result;
  }),
});

// =============================================
// العهد
// =============================================
const custodyRouter = router({
  list: protectedProcedure
    .input(z.object({
      search: z.string().optional(),
      departmentId: z.number().optional(),
      locationId: z.number().optional(),
      status: z.string().optional(),
    }).optional())
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const conditions: any[] = [];
      if (input?.search) {
        conditions.push(
          or(
            like(custodyItems.name, `%${input.search}%`),
            like(custodyItems.code, `%${input.search}%`)
          )
        );
      }
      if (input?.departmentId) conditions.push(eq(custodyItems.departmentId, input.departmentId));
      if (input?.locationId) conditions.push(eq(custodyItems.locationId, input.locationId));
      if (input?.status) conditions.push(eq(custodyItems.status, input.status));

      const where = conditions.length > 0 ? and(...conditions) : undefined;

      const rows = await db
        .select({
          id: custodyItems.id,
          name: custodyItems.name,
          code: custodyItems.code,
          quantity: custodyItems.quantity,
          assetValue: custodyItems.assetValue,
          condition: custodyItems.condition,
          assignedTo: custodyItems.assignedTo,
          employeeName: employees.fullName,
          departmentId: custodyItems.departmentId,
          departmentName: departments.name,
          locationId: custodyItems.locationId,
          locationName: locations.name,
          status: custodyItems.status,
          notes: custodyItems.notes,
          assetImagePath: custodyItems.assetImagePath,
          invoiceImagePath: custodyItems.invoiceImagePath,
          excludedQuantity: custodyItems.excludedQuantity,
          createdAt: custodyItems.createdAt,
          updatedAt: custodyItems.updatedAt,
        })
        .from(custodyItems)
        .leftJoin(employees, eq(custodyItems.assignedTo, employees.id))
        .leftJoin(departments, eq(custodyItems.departmentId, departments.id))
        .leftJoin(locations, eq(custodyItems.locationId, locations.id))
        .where(where)
        .orderBy(desc(custodyItems.createdAt));

      return rows;
    }),

  getById: protectedProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const [row] = await db
        .select({
          id: custodyItems.id,
          name: custodyItems.name,
          code: custodyItems.code,
          quantity: custodyItems.quantity,
          assetValue: custodyItems.assetValue,
          condition: custodyItems.condition,
          assignedTo: custodyItems.assignedTo,
          employeeName: employees.fullName,
          departmentId: custodyItems.departmentId,
          departmentName: departments.name,
          locationId: custodyItems.locationId,
          locationName: locations.name,
          status: custodyItems.status,
          notes: custodyItems.notes,
          assetImagePath: custodyItems.assetImagePath,
          invoiceImagePath: custodyItems.invoiceImagePath,
          excludedQuantity: custodyItems.excludedQuantity,
          createdAt: custodyItems.createdAt,
        })
        .from(custodyItems)
        .leftJoin(employees, eq(custodyItems.assignedTo, employees.id))
        .leftJoin(departments, eq(custodyItems.departmentId, departments.id))
        .leftJoin(locations, eq(custodyItems.locationId, locations.id))
        .where(eq(custodyItems.id, input.id))
        .limit(1);
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "العهدة غير موجودة" });
      return row;
    }),

  create: protectedProcedure
    .input(z.object({
      name: z.string().min(1).max(500),
      code: z.string().max(100).optional().nullable(),
      quantity: z.number().min(1).default(1),
      assetValue: z.string().optional().nullable(),
      condition: z.string().max(50).optional().nullable(),
      assignedTo: z.number().optional().nullable(),
      departmentId: z.number().optional().nullable(),
      locationId: z.number().optional().nullable(),
      notes: z.string().optional().nullable(),
      assetImagePath: z.string().optional().nullable(),
      invoiceImagePath: z.string().optional().nullable(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const result = await db.insert(custodyItems).values({
        name: input.name,
        code: input.code || null,
        quantity: input.quantity,
        assetValue: input.assetValue || "0",
        condition: input.condition || "جيد جدًا",
        assignedTo: input.assignedTo || null,
        departmentId: input.departmentId || null,
        locationId: input.locationId || null,
        notes: input.notes || null,
        assetImagePath: input.assetImagePath || null,
        invoiceImagePath: input.invoiceImagePath || null,
        status: "ACTIVE",
      });
      const insertId = Number(result[0].insertId);
      // أرشفة تلقائية عند إضافة عهدة جديدة
      try {
        await upsertArchiveDocument({
          db,
          entityType: "custody",
          entityId: insertId,
          entityName: input.name,
          entityCode: input.code || null,
          employeeName: null,
          departmentName: null,
          locationName: null,
          quantity: input.quantity,
          assetValue: input.assetValue || null,
          condition: input.condition || null,
          status: "ACTIVE",
          notes: input.notes || null,
          assetImagePath: input.assetImagePath || null,
          createdBy: ctx.user.id,
          isUpdate: false,
        });
      } catch (archiveErr) {
        console.error("[Archive] فشل إنشاء سجل الأرشيف:", archiveErr);
      }
      await logAuditAction({
        tableName: "custody_items",
        recordId: insertId,
        actionType: "CREATE",
        actionDescription: `إضافة عهدة: ${input.name}`,
        newData: input,
        performedBy: ctx.user.id,
        performedByName: ctx.user.name || undefined,
        ipAddress: ctx.req.ip || undefined,
        userAgent: ctx.req.headers["user-agent"] || undefined,
      });
      return { id: insertId };
    }),

  update: protectedProcedure
    .input(z.object({
      id: z.number(),
      name: z.string().min(1).max(500),
      code: z.string().max(100).optional().nullable(),
      quantity: z.number().min(1).default(1),
      assetValue: z.string().optional().nullable(),
      condition: z.string().max(50).optional().nullable(),
      assignedTo: z.number().optional().nullable(),
      departmentId: z.number().optional().nullable(),
      locationId: z.number().optional().nullable(),
      status: z.string().max(30).optional(),
      notes: z.string().optional().nullable(),
      assetImagePath: z.string().optional().nullable(),
      invoiceImagePath: z.string().optional().nullable(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const [old] = await db.select().from(custodyItems).where(eq(custodyItems.id, input.id)).limit(1);
      if (!old) throw new TRPCError({ code: "NOT_FOUND" });
      const { id, ...updateData } = input;
      await db.update(custodyItems).set({
        name: updateData.name,
        code: updateData.code || null,
        quantity: updateData.quantity,
        assetValue: updateData.assetValue || "0",
        condition: updateData.condition || null,
        assignedTo: updateData.assignedTo || null,
        departmentId: updateData.departmentId || null,
        locationId: updateData.locationId || null,
        status: updateData.status || old.status,
        notes: updateData.notes || null,
        assetImagePath: updateData.assetImagePath || null,
        invoiceImagePath: updateData.invoiceImagePath || null,
      }).where(eq(custodyItems.id, id));
      // تحديد الحقول المتغيرة
      const changedFields: string[] = [];
      if (old.name !== updateData.name) changedFields.push('name');
      if (old.code !== (updateData.code || null)) changedFields.push('code');
      if (old.quantity !== updateData.quantity) changedFields.push('quantity');
      if (old.assetValue !== (updateData.assetValue || '0')) changedFields.push('assetValue');
      if (old.condition !== (updateData.condition || null)) changedFields.push('condition');
      if (old.assignedTo !== (updateData.assignedTo || null)) changedFields.push('assignedTo');
      if (old.departmentId !== (updateData.departmentId || null)) changedFields.push('departmentId');
      if (old.locationId !== (updateData.locationId || null)) changedFields.push('locationId');
      if (old.status !== (updateData.status || old.status)) changedFields.push('status');
      if (old.notes !== (updateData.notes || null)) changedFields.push('notes');

      // أرشفة تلقائية عند تعديل عهدة
      try {
        await upsertArchiveDocument({
          db,
          entityType: "custody",
          entityId: id,
          entityName: updateData.name,
          entityCode: updateData.code || null,
          employeeName: null,
          departmentName: null,
          locationName: null,
          quantity: updateData.quantity,
          assetValue: updateData.assetValue || null,
          condition: updateData.condition || null,
          status: updateData.status || old.status,
          notes: updateData.notes || null,
          assetImagePath: updateData.assetImagePath || null,
          createdBy: ctx.user.id,
          isUpdate: true,
        });
      } catch (archiveErr) {
        console.error("[Archive] فشل تحديث سجل الأرشيف:", archiveErr);
      }
      await logAuditAction({
        tableName: "custody_items",
        recordId: id,
        actionType: "UPDATE",
        actionDescription: `تعديل عهدة: ${input.name} - تغيير ${changedFields.length} حقل`,
        oldData: old,
        newData: updateData,
        changedFields,
        performedBy: ctx.user.id,
        performedByName: ctx.user.name || undefined,
        ipAddress: ctx.req.ip || undefined,
        userAgent: ctx.req.headers["user-agent"] || undefined,
      });
      return { success: true };
    }),

  delete: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const [old] = await db.select().from(custodyItems).where(eq(custodyItems.id, input.id)).limit(1);
      if (!old) throw new TRPCError({ code: "NOT_FOUND" });
      await db.delete(custodyItems).where(eq(custodyItems.id, input.id));
      await logAuditAction({
        tableName: "custody_items",
        recordId: input.id,
        actionType: "DELETE",
        actionDescription: `حذف عهدة: ${old.name}`,
        oldData: old,
        performedBy: ctx.user.id,
        performedByName: ctx.user.name || undefined,
        ipAddress: ctx.req.ip || undefined,
        userAgent: ctx.req.headers["user-agent"] || undefined,
      });
      return { success: true };
    }),

  stats: protectedProcedure.query(async () => {
    const db = await getDb();
    if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
    const [result] = await db
      .select({
        total: sql<number>`COUNT(*)`,
        totalValue: sql<string>`COALESCE(SUM(CAST(${custodyItems.assetValue} AS DECIMAL(12,2)) * ${custodyItems.quantity}), 0)`,
        activeCount: sql<number>`SUM(CASE WHEN ${custodyItems.status} = 'ACTIVE' THEN 1 ELSE 0 END)`,
      })
      .from(custodyItems);
    return result;
  }),
});

export const inventoryRouter = router({
  assets: assetsRouter,
  custody: custodyRouter,
});
